### ISSUE TITLE
Have the ability to pin a comment on the Chat

### ISSUE THREAD

**Issue by MattyAyOh** [betty-labs/issues#4612]
**What happened:**
```
Have the ability to pin a comment on the Chat
```

**Version:** 2.0.2 (159)

**Operating system:** iOS 14.6

**Model:** iPhone XS

**Memory:** 96% (2.78 GB used out of 2.9 GB)

**Capacity:** 98% (232 GB used out of 238 GB)

**Locale:** United States English

**User identifier:** itsjustmy2cents

**Network:** AT&T LTE (4G)

**WiFi:** Connected

**Logs:** [View](http://buglife.com/apps/locker-room/reports/4099/awesome_logs) 

**Attachments:** 

![Screenshot.png](http://buglife.s3.amazonaws.com/report_attachments/96afed30f7c6fb2d5df997efa20a3948116806d0/original/Screenshot.png?1624217703)

**URL:** http://buglife.com/apps/locker-room/reports/4099

Reported via Buglife

**Comment by sczizzo** [comment]
Moved to https://jira.spotify.net/browse/GB-190
