### ISSUE TITLE
Deprecate external-data service with distributed tracing

### ISSUE THREAD

**Issue by descent3me** [betty-labs/issues#6551]
From GreenRoom / Core Infra sprint board https://jira.spotify.net/browse/LM-70

https://github.com/betty-labs/external-data

The required changes can be made by doing the following.

go get github.com/betty-labs/betty-server && go mod tidy 

Example https://github.com/betty-labs/disco-server/pull/506

Check for other types of upstream requests that aren't using the already instrumented Postgres and Redis clients from betty-server and instrumenting them as well. See https://github.com/betty-labs/query-service/pull/58/files#diff-ad948edf3e97fa6583cdddbeb02df70d49c337c5e1309d95903fdd42a9f980c4R31-R43

**Comment by sczizzo** [comment]
Tis done
