### ISSUE TITLE
Removing autocapitalization

### ISSUE THREAD

**Issue by ewsimonds** [betty-labs/issues#7081]
**Is your feature request related to a problem? Please describe.**
The app currently forces the first letter of first and last names to be capitalized. Some users (like artists) style their names in all lowercase, and there's no way to do that without editing directly in the database, which gets overridden if the user then edits another piece of their profile.

**Describe the solution you'd like**
Remove autocapitalization.

**Describe alternatives you've considered**
To date, I have just had priority users edit their profile and confirm satisfaction before requesting a Greenroom engineer to edit the name case on the backend.

**Additional context**
Would like to be able to do this within the next two to three weeks if possible to accommodate some artists who will be hosting Wrapped events on Greenroom around December 5-7.

**Comment by sczizzo** [comment]
Moved to https://jira.spotify.net/browse/GB-179
