### ISSUE TITLE
Move from "Groups" to "Topics" throughout app

### ISSUE THREAD

**Issue by ttraviskanee** [betty-labs/issues#7143]
There is a lot of confusion around the word "Group" so to clear this up we are changing to "Topics" there are several touch points affected by this throughout the app, documented in the screenshots/figma.

<img width="1736" alt="Screen Shot 2021-12-06 at 10 21 15 AM" src="https://user-images.githubusercontent.com/87726290/144900663-5e78b7ed-8fc4-4902-a451-998e570d6ea4.png">
<img width="2378" alt="Screen Shot 2021-12-06 at 10 20 56 AM" src="https://user-images.githubusercontent.com/87726290/144900671-b5a939a8-bdb3-4e93-b342-955c32f59352.png">
<img width="1754" alt="Screen Shot 2021-12-06 at 10 25 10 AM" src="https://user-images.githubusercontent.com/87726290/144901199-6a8256d7-f1ef-4a96-a166-e581ab2067c9.png">

https://www.figma.com/file/fbmf3sZwVcU6duiYYAaMj2/Home-feed?node-id=1145%3A175260

This also includes some minor updates to the create screen (placeholder in text fields, "optional" label on fields, surfacing topics on main screen) Will need to coordinate with @ewsimonds to show curated list of popular topics by default

**Comment by thesultanster** [comment]
no
