### ISSUE TITLE
Play Store Listing needs to be updated?

### ISSUE THREAD

**Issue by MattyAyOh** [betty-labs/issues#7231]
Thanks Vivian!

I am normally only the RM for the main app but checking Google Play console, I see the following apps in production.

I can do the updates for the apps above if the teams themselves cannot do it and if it is easier for you, but for Greenroom updates should be done separately as they have a separate entity in Google Play and I do not have access. I am adding Matt and Andrew who are the Greenroom contacts that I believe you should provide the csv file to.

Regards,

Aysegul

**Comment by thesultanster** [comment]
@andrzli A bit confused about this ticket. Is this related to the Play store app migration?

**Comment by andrzli** [comment]
let's close this - we'll need to update as part of the rebrand (not directly because of the play store migration), but this was opened in jan 6
