### ISSUE TITLE
"Host URI" text fields shows in upcoming room creation page for non-admin accounts

### ISSUE THREAD

**Issue by EmilySeal** [betty-labs/issues#7352]
**Describe the bug**
When in the room creation page for an upcoming room, non-admin accounts are seeing the text field to put a Host URI. 

**To Reproduce**
1. With a non-admin account, schedule an upcoming room
2. Click "New room"  and click on "Create scheduled room"
3. In the room creation page you will see the "Host URI" text field

**Expected behavior**
Only an admin account should see this option

**Smartphone (please complete the following information):**
 - Device: Galaxy A32 & Pixel 5
 - OS: Android 11
 - App Version: 2.0.46

**Additional context**
-Only an issue on Android devices
-Regular accounts do not see this option when creating regular, non-scheduled rooms

**Comment by EmilySeal** [comment]
@usamir Hey so I just retested this and it seems like the issue has been fixed. Using a non-admin account I do not see the option to put in a host URI, and as an admin I do. I think this one should be good to close.

**Comment by usamir** [comment]
issues is fixed
